services:
  api:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - SECRET_KEY=${SECRET_KEY}
    command: ["fastapi", "run", "app/main.py", "--port", "8000"]
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dtLabs
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  test:
    build: .
    command: ["pytest"]
    environment:
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - api